name: brazil
description: Function-oriented library for generating, validating and formatting brazilian values such as CPF and CNPJ.

version: 1.0.0
homepage: https://www.github.com/gumbarros/brazil.dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0