name: brazil
description: Function-oriented library for generating, validating and formatting Brazilian values such as CPF and CNPJ.

version: 0.2.0
homepage: https://www.github.com/gumbarros/brazil.dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0
  
